import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import Link from 'next/link';

import { Character, GetCharactersResults } from '@/types/characters';

type Props = {
  characters: Character[];
  previous: string | null;
  next: string | null;
};

export const Home: NextPage<Props> = ({ characters, previous, next }) => {
  return (
    <>
      <Head>
        <title>Wannabe Challenge</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <header className="mt-3">
          <h1>Star Wars Characters</h1>
          <hr />
        </header>
      </main>

      <ul className="list-group">
        {characters.map((character: Character) => (
          <li key={character.name} className="list-group-item">
            {character.name}
          </li>
        ))}
      </ul>

      <div className="container-sm text-center mt-5">
        <button className="btn btn-primary me-5" disabled={previous ? false : true} type="button">
          Previous Page
        </button>
        <button className="btn btn-primary" disabled={next ? false : true} type="button">
          <Link href="/2">Next Page</Link>
        </button>
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch('https://swapi.dev/api/people/');
  const { previous, next, results }: GetCharactersResults = await response.json();

  return {
    props: {
      characters: results,
      previous,
      next,
    },
  };
};
