import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import { Character, GetCharactersResults } from '@/types/characters';
import CharactersList from '@/components/CharactersList';

type Props = {
  characters: Character[];
  previous: string | null;
  next: string | null;
};

export const Home: NextPage<Props> = ({ characters, previous, next }) => {
  const route = useRouter();

  const page = Number(route.query.page);

  return (
    <>
      <Head>
        <title>Wannabe Challenge</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <CharactersList characters={characters} title="Star Wars Characters" />

      <div className="container-sm text-center mt-5">
        <button className="btn btn-primary me-5" disabled={previous ? false : true} type="button">
          <Link href={`/${page - 1}`}>Previous Page</Link>
        </button>
        <button className="btn btn-primary" disabled={next ? false : true} type="button">
          <Link href={`/${page ? page + 1 : 2}`}>Next Page</Link>
        </button>
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const response = await fetch('https://swapi.dev/api/people/');
    const { previous, next, results }: GetCharactersResults = await response.json();

    if (!response.ok) {
      return { notFound: true };
    }

    return {
      props: {
        characters: results,
        previous,
        next,
      },
    };
  } catch (err) {
    return { notFound: true };
  }
};
